### ISSUE TITLE
Text search with index

### ISSUE THREAD

**Issue by BenoitPingris** [Kamva/mgm#10]
I'd like to perform a full-text search in one of my collection but can't figure out how to do it with mgm.

I did not find a lot of resources online for the basic mongo-driver for golang. The most relevant one was this [one](https://medium.com/easyread/today-i-learn-text-search-on-mongodb-6b87cd8497c9) 

I tried to translate this with mgm, first by getting the `mongo.Collection` out of the mgm one:
```golang
coll.Collection.Indexes().CreateOne(mgm.Ctx(), ...)
```

But I must say I have been blocked quickly !

The signature of this function is the following:
```golang
func (mongo.IndexView).CreateOne(ctx context.Context, model mongo.IndexModel, opts ...*options.CreateIndexesOptions) (string, error)
```

How can I do to use a mgm custom model, and transform it in some way to pass it as a `mongo.IndexModel` argument to CreateOne function ? 

If I have misinterpreted something or miss anything relevant, please tell me !
mondo.IndexMode
Thank you !

**Comment by mehran-prs** [comment]
Hi, @BenoitPingris 

`IndexModel` is just like a mongo option and is not relevant to the MGM Models.
you can simply create your index and then search.

A sample code:

- Create `text` Index on `name` & `description` fields.
```go
mod := mongo.IndexModel{Keys: bson.M{"name": "text", "description": "text"}}
name, err := mgm.Coll(&Book{}).Indexes().CreateOne(mgm.Ctx(), mod)
if err != nil {
	panic(err)
}
fmt.Println("Index name: ", name)
```
- Search in books (assume our model is `Book`)
```go 
books := make([]Book, 0)
_ = mgm.Coll(&Book{}).SimpleFind(&books, bson.M{operator.Text: bson.M{"$search": "hello"}})
```

**Comment by BenoitPingris** [comment]
Ok thank you, I'll try with this !
