### ISSUE TITLE
Count and Pagination

### ISSUE THREAD

**Issue by YoshieraHuang** [Kamva/mgm#16]
**Is your feature request related to a problem? Please describe.**
I think count and pagination will be very helpful for collection with large entries.

**Describe the solution you'd like**
New `Count` and `Find` functions attached to `Collection` struct seems a good solution. The functions accept a option struct argument which contains filter or pagination arguments.

**Describe alternatives you've considered**

**Additional context**

**Comment by mehran-prs** [comment]
Hi @YoshieraHuang, 
Yes but you can simply achieve it by using filter options. some thing like this
```golang
err := mycollection.SimpleFind(&items,bson.M{}, &options.FindOptions{
		Limit: &limit,
		Skip:  &offset,
})
```

**Comment by YoshieraHuang** [comment]
> Hi @YoshieraHuang,
> Yes but you can simply achieve it by using filter options. some thing like this
> 
> ```go
> err := mycollection.SimpleFind(&items,bson.M{}, &options.FindOptions{
> 		Limit: &limit,
> 		Skip:  &offset,
> })
> ```

OK, Thank you so much

**Comment by YoshieraHuang** [comment]
I will close this issue
