### ISSUE TITLE
How to integrate mongo-migrate package 

### ISSUE THREAD

**Issue by lukekhamilton** [Kamva/mgm#17]
**Is your feature request related to a problem? Please describe.**

I need a way to add mongo db migration support into my app that using mgm for all mongodb stuff. 

Was thinking of using this package: https://github.com/xakep666/mongo-migrate

Looks like I just need a way to access the underlying db var for this to work. But couldnt see if there is a way already in the package to access this? 

**Describe the solution you'd like**

I think I just need a way to access the db object. 

**Describe alternatives you've considered**

nothing yet.

**Comment by mehran-prs** [comment]
Hi @lukekhamilton 
 Just call the `DefaultConfigs()` function:

```golang
cfg, client, db, er := mgm.DefaultConfigs()
```

**Comment by lukekhamilton** [comment]
Thanks
