### ISSUE TITLE
How can I maintain multiple db connections?

### ISSUE THREAD

**Issue by mr-kashif** [Kamva/mgm#19]
I would like to connect to multiple databases and perform CRUD operations selectively on each request. How can I do that using this library?

**Comment by mehran-prs** [comment]
You just need to the `Collection` method on your collection, it should return the collection by your config, something like this:

```go
func (model *Book) Collection() *mgm.Collection {
    // You can also create your cystom client here....
   _,client,_, err := mgm.DefaultConfigs()

   if err != nil {
      panic(err)
   }

   // Choose your database by checking something here...
   db := client.Database("another_db")
   return mgm.NewCollection(db, "my_collection")
}
```

And if you want to selectively enable this feature on some or all collections, you can just implement your custom `Coll` method which gets the Model instance and return db base on specific config.

**Comment by mr-kashif** [comment]
Hi @mehran-prs.

Thanks for the reply. I made a utility func for all models.

```go
// DBColl returns collections of required databse
func DBColl(dbName string, m mgm.Model) *mgm.Collection {
	_, client, _, err := mgm.DefaultConfigs()
	if err != nil {
		log.Println(err)
	}

	return mgm.NewCollection(client.Database(dbName), mgm.CollName(m))
}
```
