### ISSUE TITLE
how can I exec multi crud in one transaction?

### ISSUE THREAD

**Issue by exfly** [Kamva/mgm#2]

**Comment by mehran-prs** [comment]
Hi @exfly 
update your package version to `1.1.1` and then:

- To run a transaction on default connection use `mgm.Transaction()` function, e.g:
```go
d := &Doc{Name: "check", Age: 10}

err := mgm.Transaction(func(session mongo.Session, sc mongo.SessionContext) error {

       // do not forget to use our methods with the context of the session.
	err := mgm.Coll(d).SaveWithCtx(sc, d)

	if err != nil {
		return err
	}

	return session.CommitTransaction(sc)
})
```

- To run a transaction with your context, use `mgm.TransactionWithCtx()` method.
- To run a transaction on another connection, use `mgm.TransactionWithClient()` method.

And finally, if you want to use fully customized transactions, just need to get default connection client by `_,client,db,_:=mgm.DefaultConfigs()` and then using raw MongoDB driver transactions.
