### ISSUE TITLE
bson.M type does not implement Context

### ISSUE THREAD

**Issue by Lowl11** [Kamva/mgm#21]
**Description of the bug**
I tried to use package by a tutorial in README. And first thing I wanted to do is get one record by field (filter).
Then I used this line of code from README `coll.FindOne(bson.M{"id": userID}, user)` to get record.

**Shortly**
Impossible to use `bson.M{}` because lint says:
"Cannot use 'bson.M{"id": userID}' (type M) as type context.Context Type does not implement 'context.Context' as some methods are missing: Deadline() (deadline time.Time, ok bool) Done() <-chan struct{} Err() error ..."

**Screenshot**
![image](https://user-images.githubusercontent.com/34792286/89735506-c42c5780-da84-11ea-8fb0-3301fc5966f6.png)

**Possible solution the issue**
![image](https://user-images.githubusercontent.com/34792286/89735614-a9a6ae00-da85-11ea-93b6-eb15b90cb591.png)
I am not sure in that solution!

**Environment:**
 - Golang Version: 1.14
 - mgm version (tag): 3.0.1

**Comment by mehran-prs** [comment]
Your provided params are wrong, the first param of `FindOne` method must be a context not a `bson.M`.
Something like this:
```go
coll := mgm.Coll(&Book{})
coll.FindOne(ctx,bson.M{})
```

I think you want to use the `First` method:
```go
coll.First(bson.M{"id": userID}, user)
```
