### ISSUE TITLE
Auth fails with mongodb atlas cluster

### ISSUE THREAD

**Issue by itzmanish** [Kamva/mgm#22]
**Describe the bug**
"connection() : auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AtlasError) Authentication failed.

Everything was working fine till today I get error with authentication failed. I didn't changed anything, not a single line of code but still I get error on any operation with mgm `connection() : auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AtlasError) Authentication failed.`

**To Reproduce**
1. 
```
err = mgm.SetDefaultConfig(nil, "directory", options.Client().ApplyURI(os.Getenv("MONGODB_URI")))
if err != nil {
	log.Fatal(err)
}
```
2. Export MONGODB_URI with mongodb atlas cluster uri.
3. Run the server.
4. Do Some operation.

**Expected behavior**
Operation should complete without any error.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by mehran-prs** [comment]
Hi @itzmanish 
Please check you authentication data by login manually to you DB, I think this is because of wrong `AuthenticationDatabase` or `username|password` in your DB URI. 
Maybe you enabled authentication recently in your Atlas cluster and you should check your DB authentication data.

**Comment by itzmanish** [comment]
> Please check you authentication data by login manually to you DB, I think this is because of wrong AuthenticationDatabase or username|password in your DB URI.
Not the case. I was using for a long time with same setup.

However something weird I have seen that official mongo driver gives me same error but when I pass credential option with username and password it works. Don't know why this issue didn't occur before.

**Comment by mehran-prs** [comment]
Print your URI before connection, maybe it's not what you expected.
I'll close this issue, but if you need some help, comment here.

**Comment by mehran-prs** [comment]
Just like this?   
`mongodb://{username}:{password}@{your host}:27017/{yourdb}?authSource={admin or your authentication database}`

use command line command (like `mongo "mongodb://test:testpwd@localhost/test?authSource=admin"`) and check it, because I think just URI can cause this error.
