### ISSUE TITLE
Issues running an update query using "FindOneAndUpdate()"

### ISSUE THREAD

**Issue by darienmiller88** [Kamva/mgm#25]
I'm currently building an Echo app using this library, and it has worked wonderfully for 3 out of the four query's, with update being the only one not working. I am getting the error "update document must contain key beginning with '$' ".  I'm not exactly sure what it wants me to do here, as adding a "$" to the front of the key causes another error message "(FailedToParse) Unknown modifier: $content". Here's a small code snippet

Model:

```
//Tweed is an object meant to define the skeleton of the "tweed" form on the front end.
type Tweed struct{
	mgm.DefaultModel `bson:",inline"`
	Name    string `json:"name" bson:"name"`
	Content string `json:"content" bson:"content"`
}


```

Update Query:

```

	 	result := mgm.CollectionByName("tweeds").FindOneAndUpdate(
			mgm.Ctx(),

                         //Adding a "$" in front of content causes the second error.
			bson.M{"content": updateParameters["content"]},

			bson.M{"content": updateParameters["updated_content"]},
		)

```

What am I missing with my query?

**Comment by mehran-prs** [comment]
In update section you should use an `update Operator`, In your case use `$set`, test something like this :
```go
result := mgm.CollectionByName("tweeds").FindOneAndUpdate(
			mgm.Ctx(),

                         //Adding a "$" in front of content causes the second error.
			bson.M{"content": updateParameters["content"]},

			bson.M{"$set":bson.M{"content": updateParameters["updated_content"]}},
		)
```

**Comment by darienmiller88** [comment]
Ahh, perfect! That worked, thank you!
