### ISSUE TITLE
ID, created_at, updated_at is not generated with nested field

### ISSUE THREAD

**Issue by ksewo** [Kamva/mgm#26]
**Describe the bug**
When using mgm model with mgm.DefaultModel in nested struct inside model, ID, created_at and updated_at of this struct is not updated when using Save() and Update().

**To Reproduce**
Save/Update model with nested struct that has mgm.DefaultModel. Saved/Updated collection does have null _id, created_at and updated_at fields.

Example model:
```go
type GameReview struct {
  mgm.DefaultModel `bson:",inline"`
  Content string `bson:"content"`
}

type Game struct {
  mgm.DefaultModel  `bson:",inline"`
  Name string `bson:"name"`
}
```

**Expected behavior**
ID, created_at and updated_at fields should be updated.

**Environment (please complete the following information):**
 - Ubuntu 20.04
- go1.14.7

Due to the nature of the error, it will occur on every environment.

**Comment by mehran-prs** [comment]
In our tests, the default fields get new values on update or save.
Provide complete example code to reproduce the bug, please.

Please note:
- `_id`, `created_at` and `updated_at` generate by `mgm` hooks.
- Each model by default uses the `Creating` and `Saving` hooks, So if you want to define those hooks, call `DefaultModel ` hooks in your defined hooks.
- collection's methods which call to the hooks:
   - `Create` & `CreateWithCtx`
   - `Update` & `UpdateWithCtx` 
   - `Delete` &` DeleteWithCtx`

**Comment by ksewo** [comment]
@mehran-prs thanks for your response. _id, created_at and updated_at are updated only in main model, not in nested structs.

Example code:

```go
type GameReview struct {
  mgm.DefaultModel `bson:",inline"`
  Content string `bson:"content"`
}

type Game struct {
  mgm.DefaultModel  `bson:",inline"`
  Name string `bson:"name"`
  Reviews []GameReview `bson:"reviews"`
}

gameColl := mgm.Coll(&Game{})

gameColl.Save(Game{
  Name: "Minecraft",
  Reviews: []GameReview{
    GameReview{
      Content: "Great game!"
    },
  },
})
```

Using this code game has ID, created_at and updated_at fields with their good values, but reviews[0], does have null ID and created_at, updated_at fields equal to 0001-01-01T00:00:00Z.

**Comment by mehran-prs** [comment]
@ksewo mgm does not support hooks for nested structs, we just support the root.
I think you can write three hooks for your root model and on those hooks, call your nested structs and generate data for those.
something like this:
e.g.,
```go

type Book struct {
	mgm.DefaultModel
	Name string `json:"name" bson:"name"`
}

// Created hook
func (b *Book) Creating(id interface{}) error {
	if err := b.DefaultModel.Creating(); err != nil {
		return err
	}
	// Generate Id for your nested structs.
	// Set "created_at" date on your nested structs. 
	return nil
}

// Saving hook
func (b *Book) Saving() error {
	if err := b.DateFields.Saving(); err != nil {
		return err
	}
	// Update the "updated_at" field in your nested structs.
	return nil
}

```

- Another option can be separating your data into two collections.

**Comment by mehran-prs** [comment]
@ksewo is your issue solved?
Can we close the issue?
