### ISSUE TITLE
There is a Benchmark?

### ISSUE THREAD

**Issue by eudesll** [Kamva/mgm#30]
We are evaluating to starting using `mgm` instead of `mongo-go-driver`, and I was looking for some benchmarks.

There is some, could be a good idea to create one?

**Comment by mehran-prs** [comment]
Hey @eudesll, I'm glad you want to use `mgm` in your project.
Although `mgm` is just a simple wrapper around the `mongo-go-driver`, but Yes, I think it could be a good idea to add some benchmarks.

Please feel free to submit a PR  for it ❤️
