### ISSUE TITLE
Get Create inserted ID

### ISSUE THREAD

**Issue by henri9813** [Kamva/mgm#36]
Hello,

I would like to retrieve the ID of the fresh inserted document.

Taking this snippet from the documentation:
```
book := NewBook("Pride and Prejudice", 345)

// Make sure to pass the model by reference.
err := mgm.Coll(book).Create(book)
```

I would like to retrieve the "book" ID, how can i do this without perform another search ?

Best regards

**Comment by mehran-prs** [comment]
Hi @henri9813 
`mgm` sets your model's id when you save it, you just need to pass your model __by reference__.

```golang
book:=&Book{Name:"blah blah"}
err := mgm.Coll(book).Create(book)
```
or 
```golang
book:=Book{Name:"blah blah"}
err := mgm.Coll(book).Create(&book)
```

**Comment by henri9813** [comment]
Hello,

Oh that's perfect !!

That's exactly what i want !

Thank you, maybe could you add this into the documentation ? 

Best regards

**Comment by mehran-prs** [comment]
You're welcome,
it's documentation :)
in comment of first instance creation.

> ```
>book := NewBook("Pride and Prejudice", 345)
>
>// Make sure to pass the model by reference.
>err := mgm.Coll(book).Create(book)
>```

**Comment by henri9813** [comment]
Okay, that was not explicit for me but thank you.

```
// Make sure to pass the model by reference to have it updated after the creation
```

It's better no ?

**Comment by mehran-prs** [comment]
Maybe.

**Comment by seantcanavan** [comment]
This wasn't immediately obvious to me either for what it's worth. A small piece of documentation can't hurt.

**Comment by mehran-prs** [comment]
@henri9813 Thanks for the better doc.
https://github.com/Kamva/mgm/commit/93cb042a4746084f2492df8e7ca7dc6175c814c3
