### ISSUE TITLE
Documentation of creating indexes

### ISSUE THREAD

**Issue by abrar-hnxlabs** [Kamva/mgm#45]
Currently the repo has no documentation on how to create indexes. 
It would be good to see some documentation on how to create indexes on collections. 
Even if indexes are not supported by the models it would be good to know that so alternate methods could be applied to create indexes.

**Comment by mehran-prs** [comment]
Hi @abrar-hnxlabs 
This library is a wrapper of the official MongoDB Go driver.
[Check this](https://docs.mongodb.com/manual/reference/method/db.collection.createIndex/) please.
