### ISSUE TITLE
hooks Saving and Creating not called on mongo driver native functions?

### ISSUE THREAD

**Issue by thisisdev-patrick** [Kamva/mgm#5]
in one of my mongo storage implementations, I have the following piece of code to find/update and/or upsert a record. I'm trying to get the Saving() hook to fire on my uidObj but that does not work. 

	if res := mgm.Coll(uidObj).FindOneAndUpdate(mgm.Ctx(), filter, update, &opt); res.Err() != nil {
		return res.Err()
	}

I've implemented the hook on the model like this: 

```
func (model *ObjectUID) Saving() error {
        fmt.Println("HOOK TRIGGERED") 
	if err := model.DefaultModel.Saving(); err != nil {
		return err
	}
	(*model).UpdatedAt = time.Now()
	return nil
}

```
And it does not trigger the hook. 

SO if I'm not mistaken it would be nice to have the supported native driver functions of mongo driver to trigger the hooks...

**Comment by mehran-prs** [comment]
hooks need to the model instance, so just on methods that interact with single models you have them.
methods that call to the hooks:
- `Create`  & `CreateWithCtx`
- `Update` & `UpdateWithCtx`
- `Delete` & `DeleteWithCtx` 
I think you can change your source to get the model and then update it, in this way you don't need to set `updatedAt` in the `Saving` hook, mgm handle it for you. something like this:

```
if res := mgm.Coll(uidObj).First(filter,uidObj); err != nil {
	return err
}
// Update your uidObj here
_=mgm.Coll(uidObj).Update(uidObj)
```

**Comment by joshmsamuels** [comment]
@mehran-prs It might be worth adding a method for `FindOneAndUpdate` that can do that behind the scenes. It would make the code more elegant

**Comment by mehran-prs** [comment]
In `FindOneAndUpdate` user needs to pass update data as `bson.M` type, so we will need to either :
- Use reflection to detect provided fields on the model instance and update them, also finally we can not guarantee that all of update fields passed by the user exists on the model, can be complicated. like this:
```go
func (c *Collection) FindOneAndUpdate(filter,update,model){
    model,_:=c.First(fitler,model)
 
    // Use reflection to update the data (find the model's fields by tag). 
    // but what happens if some field of update data does not exists in the model fields.
    // or maybe user set `$unset` on the provided data or using other update options

    c.Update(model)
}

```

- Or get a callback as param and we pass found model to the callback. in the callback user update the model and return it, this can be better, but using `first` and then `update` method can be simpler and don't need a callback function. using callback function can be something like this:

```go
func (c *Collection) FindOneAndUpdate(filter,update bson.M,model Model,f func(m Model)Model)error{
    model,_:=c.First(fitler,model)
    model=f(model)
    c.Update(model)
   return nil
}
```

I think We should keep everything simple.
