### ISSUE TITLE
CreatedAt is overwritten with a zero value during Save

### ISSUE THREAD

**Issue by dgunay** [Kamva/mgm#52]
**Describe the bug**

I have a model with the DefaultModel included.

I have a method which does something like the following:

```go
func  Update(dto dto.MyModel) error {
        // Convert from a DTO
	m, err := (&MyModel{}).FromDTO(dto)
	if err != nil {
		return fmt.Errorf("converting from DTO: %w", err)
	}

	if err := m.Save(); err != nil {
		return fmt.Errorf("saving model: %w", err)
	}

	return nil
}
```

The conversion from a DTO leaves `CreatedAt` as the zero-value, because that info is left out of my DTOs.

The problem is that `CreatedAt` is not declared as `omitempty`, so when I `.Save()` like this, it is overwritten with a zero value.

**To Reproduce**
1. Create a document
2. Instantiate another document struct with the same primary key and set CreatedAt to nothing (or anything you want)
3. Save the document

**Expected behavior**

Changes to `CreatedAt` are ignored, or at least ignored if `CreatedAt` is the zero value of `time.Time`.

**Screenshots**

N/A

**Environment (please complete the following information):**
 - OS: a Docker container running `golang:bullseye`

**Additional context**

As a workaround, I can stick to a get-modify-save pattern where I save the original CreatedAt time and restore it before the save instead of attempting to directly update/upsert.

**Comment by mehran-prs** [comment]
Hi @dgunay 

__Short answer__: Define your custom `DefaultModel` and use it instead of `DefaultModel` in the `mgm` package.

__In details__: If you call the `Create` or `Update` methods of the `mgm` package, the `createdAt`  field will be filled always, so the `createdAt` field shouldn't be empty, but If you want to add `omitempty` to its tag anyway, you can define your own `DefaultModel` with the `omitempty`.

**Comment by Asymons** [comment]
I've also noticed this happen recently @mehran-prs 

![image](https://user-images.githubusercontent.com/1833964/141723878-bec30809-8a01-4149-8a49-bc593c597bfc.png)

![image](https://user-images.githubusercontent.com/1833964/141723928-6c69e4d3-812f-4965-8dbc-8466812c6db7.png)

![image](https://user-images.githubusercontent.com/1833964/141723955-76c174ee-e838-4a96-8ea9-f9a5ce3e81fb.png)

Let me know if I can provide you any other information. Across multiple projects, I've noticed the timestamps being set to the zero value.

**Comment by dgunay** [comment]
> I've also noticed this happen recently @mehran-prs 
> 
> ![image](https://user-images.githubusercontent.com/1833964/141723878-bec30809-8a01-4149-8a49-bc593c597bfc.png)
> 
> ![image](https://user-images.githubusercontent.com/1833964/141723928-6c69e4d3-812f-4965-8dbc-8466812c6db7.png)
> 
> ![image](https://user-images.githubusercontent.com/1833964/141723955-76c174ee-e838-4a96-8ea9-f9a5ce3e81fb.png)
> 
> Let me know if I can provide you any other information. Across multiple projects, I've noticed the timestamps being set to the zero value.
> 

In your case (I think) if you don't use Create or Update and use the underlying MongoDB functions (InsertOne), it doesn't call any of mgm's hooks to set CreatedAt

**Comment by mehran-prs** [comment]
@dgunay I'll close this issue, please feel free to reopen it if needed.

**Comment by Asymons** [comment]
> > I've also noticed this happen recently @mehran-prs
> > ![image](https://user-images.githubusercontent.com/1833964/141723878-bec30809-8a01-4149-8a49-bc593c597bfc.png)
> > ![image](https://user-images.githubusercontent.com/1833964/141723928-6c69e4d3-812f-4965-8dbc-8466812c6db7.png)
> > ![image](https://user-images.githubusercontent.com/1833964/141723955-76c174ee-e838-4a96-8ea9-f9a5ce3e81fb.png)
> > Let me know if I can provide you any other information. Across multiple projects, I've noticed the timestamps being set to the zero value.
> 
> In your case (I think) if you don't use Create or Update and use the underlying MongoDB functions (InsertOne), it doesn't call any of mgm's hooks to set CreatedAt

Appreciate the help! I'll try using the proper methods instead
