### ISSUE TITLE
Method for MongoDB server has been found

### ISSUE THREAD

**Issue by git-Ghost** [Kamva/mgm#6]
Method for MongoDB server has been found, like mongo-go-driver provides as **Ping()** method to check. I was wondering if this framework has any alternative way of doing that. 
Reference: https://github.com/mongodb/mongo-go-driver/blob/4f5fc1942fcfbb4d32d445cec0974a4a4a11111f/mongo/client.go#L223

Thanks

**Comment by mehran-prs** [comment]
mgm create mongo-go-driver `Client` internally, so you just need to get the client function and call the `Ping` method.
```go
_,client,_,err=mgm.DefaultConfigs()
if err!=nil{
// this error always is nil, unless you do not set config but call to the `DefaultConfigs` function..
}

cilent.Ping()
```
