### ISSUE TITLE
How to prevent sql injection

### ISSUE THREAD

**Issue by upgradepa** [Kamva/mgm#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mehran-prs** [comment]
If you get the latest or this commit: 81ef3e8 (e.g., `go get github.com/kamva/mgm@81ef3e8`), you'll have these functions:
```go
func Escape(key string) string // escapes the mongo key for . and $ characters
func Unescape(key string) string // unescapes the mongo key for . and $ characters
```

Thanks to [go-mongo-key-escape](https://github.com/segment-boneyard/go-mongo-key-escape).

I'll close the issue, please feel free to reopen it.
