### ISSUE TITLE
Being able to change _id field

### ISSUE THREAD

**Issue by VyrekXD** [Kamva/mgm#80]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be cool if you can edit _id an change its type, as mongodb by itself accepts it.

```go
type Hello struct {
  Id string `bson:"_id"`
}
```

**Describe alternatives you've considered**
Using another field

**Comment by mehran-prs** [comment]
You can change it @VyrekXD 
Instead of embedding `DefailtModel` in your model  you should implement the following methods on your model (or on a struct and then embed it in your models) :

```go
// Model interface contains base methods that must be implemented by
// each model. If you're using the `DefaultModel` struct in your model,
// you don't need to implement any of these methods.
type Model interface {
	// PrepareID converts the id value if needed, then
	// returns it (e.g convert string to objectId).
	PrepareID(id interface{}) (interface{}, error)

	GetID() interface{}
	SetID(id interface{})
}
```

**Comment by mehran-prs** [comment]
> Btw this was on the docs?

I added a sentence for it in the __A  Model's Default Fields__ section on the readme of repo.

> You can even implement your own default model to customize its fields.

**Comment by VyrekXD** [comment]
> > Btw this was on the docs?
> 
> 
> 
> I added a sentence for it in the __A  Model's Default Fields__ section on the readme of repo.
> 
> 
> 
> > You can even implement your own default model to customize its fields.
> 
> 

That is really helpful. Thanks for doing a great ODM!

**Comment by VyrekXD** [comment]
![image](https://user-images.githubusercontent.com/65917996/214976434-b12efe56-e0de-4b1e-ba5d-0f558d56e716.png)
![image](https://user-images.githubusercontent.com/65917996/214976476-c988d3ff-2b70-4455-95ef-81cc302e3aa6.png)
Is this how should i be using that?

**Comment by VyrekXD** [comment]
@mehran-prs :P

**Comment by VyrekXD** [comment]
Because im confused how should i create a "default model"

**Comment by mehran-prs** [comment]
An example could be like the following struct:

```go
type MyCustomDefaultModel struct {
	ID             string `json:"id" bson:"_id,omitempty"`
	mgm.DateFields `bson:",inline"`
}

// PrepareID method prepares the ID value to be used for filtering
// e.g convert hex-string ID value to bson.ObjectId
func (f *MyCustomDefaultModel) PrepareID(id interface{}) (interface{}, error) {
	return id, nil
}

// GetID method returns a model's ID
func (f *MyCustomDefaultModel) GetID() interface{} {
	return f.ID
}

// SetID sets the value of a model's ID field.
func (f *MyCustomDefaultModel) SetID(id interface{}) {
	f.ID = id.(string)
}
`

And an example usage could be something like this:
```go
type User struct {
	MyCustomDefaultModel `bson:",inline"`
	Name string `json:"name" bson:"name"`
}
```

**Comment by VyrekXD** [comment]
Ok, ok thanks a LOT, that was the last thing  ❤️

**Comment by VyrekXD** [comment]
> An example could be like the following struct:
> 
> ```go
> type MyCustomDefaultModel struct {
> 	ID             string `json:"id" bson:"_id,omitempty"`
> 	mgm.DateFields `bson:",inline"`
> }
> 
> // PrepareID method prepares the ID value to be used for filtering
> // e.g convert hex-string ID value to bson.ObjectId
> func (f *MyCustomDefaultModel) PrepareID(id interface{}) (interface{}, error) {
> 	return id, nil
> }
> 
> // GetID method returns a model's ID
> func (f *MyCustomDefaultModel) GetID() interface{} {
> 	return f.ID
> }
> 
> // SetID sets the value of a model's ID field.
> func (f *MyCustomDefaultModel) SetID(id interface{}) {
> 	f.ID = id.(string)
> }
> ```
> 
> And an example usage could be something like this:
> 
> ```go
> type User struct {
> 	MyCustomDefaultModel `bson:",inline"`
> 	Name string `json:"name" bson:"name"`
> }
> ```

I understand it but i dont know why golang is saying to me that there is an error when doing this `guildData = models.GuildConfig{ID: "1"}`

`commands/starboard/starboard.manual.go:21:91: unknown field 'ID' in struct literal of type models.GuildConfig`
![image](https://user-images.githubusercontent.com/65917996/215287328-c86ae78a-d471-492f-97a6-ac4d0c0ede90.png)
![image](https://user-images.githubusercontent.com/65917996/215287336-1ba2928c-b59b-4df2-bbaf-2a22a2bb0aca.png)

**Comment by VyrekXD** [comment]
Or do i need to do this `models.GuildConfig{DefaultModel: models.DefaultModel{ID: ""}}`

**Comment by mehran-prs** [comment]
> Or do i need to do this models.GuildConfig{DefaultModel: models.DefaultModel{ID: ""}}

Yes @VyrekXD 
When you have an embedded struct, to set its values, you need to use this form to initialize it. or just define the model and then set its fields one by one.

> Sorry if im being to annoying

No problem :)

**Comment by VyrekXD** [comment]
Thaanks

**Comment by suntong** [comment]
Thanks a lot for the very detailed explanation @mehran-prs, 

I'm still unable to make it works, so I put in a fully implemented minimum code, at
https://github.com/suntong/lang/tree/master/lang/Go/src/db/MongoDB/mgm/crud2

When I run it, I'm getting:

```
$ ./crud
panic: interface conversion: interface {} is primitive.ObjectID, not string

goroutine 1 [running]:
main.(*MgmB).SetID(...)
        .../Go/src/db/MongoDB/mgm/crud2/mgmb.go:33
github.com/kamva/mgm/v3.create({0x96edf0, 0xc000193260}, 0xc00004a700, {0x96e4b0?, 0xc000080480?}, {0x0, 0x0, 0x0})
        .../Go/pkg/mod/github.com/kamva/mgm/v3@v3.5.0/operation.go:23 +0xd8
github.com/kamva/mgm/v3.(*Collection).CreateWithCtx(...)
        .../Go/pkg/mod/github.com/kamva/mgm/v3@v3.5.0/collection.go:55
github.com/kamva/mgm/v3.(*Collection).Create(0x96e4b0?, {0x96e4b0, 0xc000080480}, {0x0, 0x0, 0x0})
        .../Go/pkg/mod/github.com/kamva/mgm/v3@v3.5.0/collection.go:50 +0x75
main.crud()
        .../Go/src/db/MongoDB/mgm/crud2/main.go:44 +0xb1
main.main()
        .../Go/src/db/MongoDB/mgm/crud2/main.go:57 +0xf
```

So you see, 

The `ID` that I use is a shortID, a string, and it is already set during `newBook`:

![image](https://github.com/Kamva/mgm/assets/422244/104cb42e-80c0-4431-b111-5f369eeca98d)

Why this ID string becomes `primitive.ObjectID` on `main.go:44` please? Thanks.

**Comment by suntong** [comment]
Anyone? please 🙏🙏🙏
