### ISSUE TITLE
How to config to show query log?

### ISSUE THREAD

**Issue by hoangphuongcs** [Kamva/mgm#81]

**Comment by mehran-prs** [comment]
Hi @hoangphuongcs 
`mgm` is a wrapper around [mongo go driver](https://github.com/mongodb/mongo-go-driver), and Mongo go driver doesn't support query log feature, but can implement it using client's [monitor](https://github.com/mongodb/mongo-go-driver/blob/4f06ad2489b73cd1dbcebb5e7df09b77cb643be1/mongo/options/clientoptions.go#L117) option.

**Comment by mehran-prs** [comment]
@hoangphuongcs I'll close this issue, feel free to open it if needed.
