### ISSUE TITLE
go get github.com/Kamva/mgm/v2 failed

### ISSUE THREAD

**Issue by Mr-NB** [Kamva/mgm#9]
**Describe the bug**

**To Reproduce**
1.go get github.com/Kamva/mgm/v2 failed

**Screenshots**
![image](https://user-images.githubusercontent.com/35053330/83104358-22cf6f80-a0eb-11ea-95d5-acf61a1c871a.png)

**Environment (please complete the following information):**
 - OS: Linux
 - GO：1.14

**Comment by mehran-prs** [comment]
You have to set `export GO111MODULE=on` env variable.
Or maybe your `$GOPATH`, `$PATH` settings are incorrect, these should be:
```
export GOROOT=$HOME/bin/go
export GOBIN=$GOROOT/bin
export GOPATH=$HOME/golang
export PATH=$PATH:$GOBIN
```
